# https://taskfile.dev

version: '3'

vars:
  APP_NAME: grep-pdf

tasks:
  default:
    cmds:
      - task: run
  build:
    dir: cmd/{{.APP_NAME}}
    cmds:
      - go build -o {{.APP_NAME}}{{exeExt}} .
    sources:
      - ./*.go
    generates:
      - ./{{.APP_NAME}}{{exeExt}}
  run:
    dir: cmd/{{.APP_NAME}}
    deps: [ build ]
    cmds:
      - ./{{.APP_NAME}}{{exeExt}} -help
  install:
    cmds:
      - go install {{.APP_NAME}}/cmd/{{.APP_NAME}}
